spring:
  rabbitmq:
    port: 5672
    username: root
    password: root
    host: localhost
#自定义变量
mq:
  config:
    exchange: direct #交换器名称
    info:
      key: infoKey #路由键
    error:
      key: errorKey
server:
  port: 8000
